### ISSUE TITLE
some question about PrepareAA

### ISSUE THREAD

**Issue by zhang919** [jluebeck/PrepareAA#11]
Dear,
Thank you for creating such an excellent pipline, but I noticed some interesting problems. First, I noticed that the pipline does not include IndelRealign and BaseRecalibrator. Does this mean that it is not necessary for AA?
In addition, I'm noticed that you use canvas or cnvkit as CNV callers. Can you please give me more infomations what the considerations are?
Thanks for your attentions.
Best.

**Comment by jluebeck** [comment]
Hello, 

Currently we have not incorporate a wrapper for GATK into the PrepareAA pipeline. For CNV calling, PrepareAA can be used with existing CNVkit or Canvas installations. Because AA is not concerned with SNV detection, and instead concerned with breakpoint graph construction, we do not emphasize IndelRealign or BaseRecalibrator or other realignment steps prior to running AA. You are welcome to use them on your BAM file anyways.

Regarding the CNV caller which feeds input to AA. AA does not actually use CNV calls from other tools directly. AA only uses regions which pass the user-specified criteria for focal amplification seed identification. AA then uses the mean-shift algorithm to segment and call CN on those regions independently of any prior CNV information. In other words, the CNV calling step prior to running AA is only to filter down the genome to the regions the user is interested in. We obtain robust results with CNVkit, Canvas and ReadDepth across many different samples. 

If you have a bed file of CNV calls generated by an external CNV caller, you can feed these to a python script called "amplified_intervals.py" which is in the AA repository (and wrapped by default in PrepareAA). This script will select the CNV seed regions for you. 

Please feel free to ask any additional questions!

Best regards,
Jens

**Comment by zhang919** [comment]
Hello @jluebeck ,
Thank you very much for your reply and kindly. Please allow me to discuss the first qusetion further if possible, In fact, at the beginning of my work using the AA, I held the same ideas you. However,by accident, I found the accuracy of AA output looks like be imporved after apply IndelRealign and BaseRecalibrator,  sometimes even huge. For example, the following fig shows a same amp with IndelRealign and BaseRecalibrator and without.

Fig.1: https://img.vim-cn.com/70/fa7420dbca49eb5f427a4515eaf65e7e7e8db3.jpg 

Fig.2: https://img.vim-cn.com/fd/6aff427bb5219da1aefb2099a7a49969d4eb5c.jpg 

In fact, I'm confused about the difference，dose the IndelRealign produce more accurate split reads map and affects the results? Could you please give me more advice.

Best regards,
Zhang

**Comment by jluebeck** [comment]
Would you please provide the name of the aligner used to generate the BAM file used for Fig 2?

Best,
Jens

**Comment by zhang919** [comment]
I use the follow cmd to generate BAM:
bwa mem -t 16 -M -q /work/fu/bioinfo/hg38/hg38.fa trim_output/fq1.fa.gz trim_output/fq2.fa.gz

and the fig's BAM is the fig2's BAM with IndelRealign and BaseRecalibrator.
Best.
Zhang

**Comment by jluebeck** [comment]
Hi Zhang,

With regards to the original question - related to missing edges. I think in your prior edits to the response you mentioned that Fig 2 with the missing edges was AA's output after using the IndelRealigner and BaseRecalibrator, is that correct? If so, then I would advise users against using them. For AA, I would also recommend not using the "-M" flag, as this marks shorter split hits as secondary alignments, and may change how AA detects split reads from the BAM file.

Regarding your question about the Canvas file naming, that should work. However it should be unnecessary if you use `-o` to indicate a unique output directory for each sample used in your snakemake wrapper. The canvas_output_directory and CNV_GAIN.bed file are created as subdirectory of the specific `-o` -specified directory which holds all output for a sample. Does that make sense?

Best,
Jens

**Comment by zhang919** [comment]
Hi jluebeck,
Thanks for your reply, the fig2 is without IndelRealigner and BaseRecalibrator, and the fig1 is after IndelRealigner and BaseRecalibrator.
Best.
Zhang

**Comment by jluebeck** [comment]
No problem and thank you for clarifying the figures. I believe the missing
edges in figure 1 were due to the use of the -M flag with BWA.

Best,
Jens

**Comment by zhang919** [comment]
Dear @jluebeck ,
Thanks for your kindly help, I will remove -M flag to fix the problem.
Best.
Zhang
