### ISSUE TITLE
broken scripts

### ISSUE THREAD

**Issue by davidhoover** [jluebeck/PrepareAA#18]
Some of the additional scripts are broken:

* CAMPER.py     # require tkinter
* bedpe_bed_from_cycles.py  # broken with code errors
* graph_to_bed.py # requires IntervalTree

**Comment by jluebeck** [comment]
Hi, thanks much for pointing out these issues.

I have resolved the above issues in b1d426bc216de7c0b776fd7a6cb4ac7641bcf79f.  CAMPER has been switched to use a non-tkinter backend, bedpe_bed_from_cycles.py has been removed from the repo due to issues mentioned above, and the scripts importing `intervaltree` have been noted.

Thank you,
Jens
